#!/bin/bash
cd "$(dirname "$0")"

IFS="$(printf '\n\t')"   # (see https://www.dwheeler.com/essays/filenames-in-shell.html)

#
# ZSH
#
cp ~/.zshrc settings/zsh/.zshrc
cp ~/.zprofile settings/zsh/.zprofile

#
# GIT
#
cp ~/.gitconfig settings/git/.gitconfig

#
# SSH
#
cp ~/.ssh/config settings/ssh/config

#
# Karabiner
#
if [[ "$OSTYPE" == "darwin" ]]; then
  mkdir -p settings/karabiner
  cp ~/.config/karabiner/karabiner.json settings/karabiner/karabiner.json
  cp -R ~/.config/karabiner/assets settings/karabiner
fi
