#!/bin/bash
cd "$(dirname "$0")"

IFS="$(printf '\n\t')"   # (see https://www.dwheeler.com/essays/filenames-in-shell.html)

#
# ZSH
#
cp settings/zsh/.zshrc ~/.zshrc

#
# GIT
#
cp settings/git/.gitconfig ~/.gitconfig

#
# SSH
#
cp settings/ssh/config ~/.ssh/config
