#!/bin/bash
cd "$(dirname "$0")"

IFS="$(printf '\n\t')"   # (see https://www.dwheeler.com/essays/filenames-in-shell.html)

#
# ZSH
#
cp settings/zsh/.zshrc ~/.zshrc
cp settings/zsh/.zprofile ~/.zprofile

#
# GIT
#
cp settings/git/.gitconfig ~/.gitconfig

#
# SSH
#
cp settings/ssh/config ~/.ssh/config

#
# Karabiner
#
cp settings/karabiner/karabiner.json ~/.config/karabiner/karabiner.json
cp -R settings/karabiner/assets ~/.config/karabiner
