#!/bin/bash
cd "$(dirname "$0")"

IFS="$(printf '\n\t')"   # (see https://www.dwheeler.com/essays/filenames-in-shell.html)
VSCODE_SETTINGS="$HOME/Library/Application Support/Code/User"

#
# ZSH
#
cp ~/.zshrc settings/zsh/.zshrc

#
# GIT
#
cp ~/.gitconfig settings/git/.gitconfig

#
# SSH
#
cp ~/.ssh/config settings/ssh/config
